// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "VxC[dkJBb1AEs":
            case "key":return img`
................
.....ffffff.....
....ff5555ff....
...ff555555ff...
..ff55ffff55ff..
..f555f..f555f..
..f555ffff555f..
..ff55555555ff..
...ff555555ff...
....fff55fff....
......f55f......
......f55f......
......f55f......
......f55f......
......f55f......
......f55f......
......f55f......
......f55ffff...
......f55555f...
......f55ffff...
......f55f......
......f55ffff...
......f55555f...
......fffffff...
................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
